identifier: k3h1k5uel7hbj4ob
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: DonutStore
homeFolder: C:\projetos\scully\DonutStore
distFolder: dist/DonutStore
outDir: C:\projetos\scully\DonutStore\dist\static
handle404: ''
